/**
 * The authoritative list of test files `npm run test` runs, in order.
 *
 * Lifted out of `package.json` in Phase 1.1 for one concrete reason: the
 * enumerated list had grown to 8202 characters, and cmd.exe refuses a
 * command line longer than 8191. Registering two more test files made
 * `npm run test` fail on Windows with "The command line is too long" —
 * before running a single test. `scripts/run-tests.mjs` now spawns the
 * runner with this array as an argv array, which goes through CreateProcess
 * (32767-character limit) instead of the shell.
 *
 * Deliberately still an EXPLICIT list, not a glob. Three test files under
 * `src/` are intentionally not registered here, and a glob would silently
 * start running them. Registering a new test file is the same one-line
 * change it always was — it just happens in this file now.
 */
export const TEST_FILES = [
  "src/components/chat/chat-session.test.ts",
  "src/components/chat/ChatApp.ssr.test.tsx",
  "src/components/chat/chat-affordances.test.ts",
  "src/components/chat/ConceptCards.test.tsx",
  "src/components/chat/ConceptPreviewModal.test.tsx",
  "src/components/chat/DesignSummaryCard.test.tsx",
  "src/components/chat/ConceptStatusBanner.test.tsx",
  "src/components/chat/RecommendationCard.test.tsx",
  "src/components/chat/DesignerDecisionCard.test.tsx",
  "src/components/chat/design-history.test.ts",
  "src/lib/services/conversation-persistence.test.ts",
  "src/lib/services/design-brief-decision.test.ts",
  "src/capabilities/conversation/conversation-capability.test.ts",
  "src/capabilities/design-brief/design-brief-capability.test.ts",
  "src/capabilities/design-summary/design-summary-capability.test.ts",
  "src/capabilities/brief-evaluation/brief-evaluation-capability.test.ts",
  "src/capabilities/intent-extraction/intent-extraction-capability.test.ts",
  "src/capabilities/intent-extraction/product-vs-design-subject.test.ts",
  "src/capabilities/shared/brief-field-quality.test.ts",
  "src/capabilities/shared/field-normalization.test.ts",
  "src/components/chat/concept-image-fetch-controller.test.ts",
  "src/components/chat/status-poll-controller.test.ts",
  "src/capabilities/conversation/bowling-team-regression.test.ts",
  "src/capabilities/conversation/multi-scenario-regression.test.ts",
  "src/capabilities/interview-intelligence/interview-intelligence-capability.test.ts",
  "src/capabilities/product-intelligence/product-intelligence-capability.test.ts",
  "src/capabilities/revision-intelligence/revision-intelligence-capability.test.ts",
  "src/capabilities/revision-timeline/revision-timeline-capability.test.ts",
  "src/capabilities/regeneration-intelligence/regeneration-intelligence-capability.test.ts",
  "src/capabilities/concept-generation/concept-generation-capability.test.ts",
  "src/capabilities/concept-generation/concept-generation-pipeline.test.ts",
  "src/capabilities/conversation/conversation-revision.test.ts",
  "src/capabilities/shared/retry.test.ts",
  "src/capabilities/prompt-translation/prompt-translation-capability.test.ts",
  "src/capabilities/prompt-translation/creative-reference-extraction.test.ts",
  "src/lib/domain/concept-directions.test.ts",
  "src/capabilities/concept-evaluation/concept-evaluation-capability.test.ts",
  "src/capabilities/concept-evaluation/concept-evaluation-pipeline.test.ts",
  "src/capabilities/concept-evaluation/openai-concept-evaluation-provider.test.ts",
  "src/capabilities/concept-evaluation/resolve-concept-evaluation-provider.test.ts",
  "src/lib/config/concept-evaluation-provider-config.test.ts",
  "src/capabilities/providers/openai-concept-provider.test.ts",
  "src/capabilities/providers/concept-prompt-fidelity.test.ts",
  "src/capabilities/providers/no-text-contract.test.ts",
  "src/capabilities/assets/asset-capability.test.ts",
  "src/lib/config/generation-provider-config.test.ts",
  "src/lib/config/asset-storage-config.test.ts",
  "src/capabilities/providers/resolve-concept-provider.test.ts",
  "src/capabilities/concept-generation/concept-generation-unavailable.test.ts",
  "src/capabilities/concept-generation/concept-generation-production-safety.test.ts",
  "src/capabilities/asset-storage/signed-url-token.test.ts",
  "src/capabilities/asset-storage/filesystem-asset-storage-provider.test.ts",
  "src/capabilities/asset-storage/resolve-asset-storage-provider.test.ts",
  "src/capabilities/asset-storage/supabase-storage-asset-provider.test.ts",
  "src/capabilities/assets/png-thumbnail-generator.test.ts",
  "src/capabilities/generation-worker/generation-worker-capability.test.ts",
  "src/capabilities/generation-worker/generation-worker-concurrency.test.ts",
  "src/capabilities/generation-worker/generation-worker-regeneration.test.ts",
  "src/lib/services/conversation-service.test.ts",
  "src/app/api/assets/[...objectKey]/route.test.ts",
  "src/app/api/projects/[projectId]/generation/status/route.test.ts",
  "src/app/api/projects/[projectId]/finalization/status/route.test.ts",
  "src/app/api/projects/[projectId]/concepts/[artworkVersionId]/image/route.test.ts",
  "src/lib/config/worker-config.test.ts",
  "src/capabilities/worker-scheduler/worker-auth.test.ts",
  "src/capabilities/worker-scheduler/worker-rate-limiter.test.ts",
  "src/capabilities/worker-scheduler/worker-scheduler-capability.test.ts",
  "src/lib/db/supabase-store.generation-jobs.test.ts",
  "src/app/api/worker/generation/route.test.ts",
  "src/capabilities/conversation-understanding/conversation-understanding-capability.test.ts",
  "src/capabilities/conversation-understanding/openai-conversation-understanding-provider.test.ts",
  "src/capabilities/conversation-understanding/resolve-conversation-understanding-provider.test.ts",
  "src/lib/config/conversation-understanding-provider-config.test.ts",
  "src/capabilities/intent-extraction/reconcile-understanding.test.ts",
  "src/capabilities/intent-extraction/detailed-description-fidelity.test.ts",
  "src/capabilities/intent-extraction/multi-turn-design-intent.test.ts",
  "src/capabilities/intent-extraction/intent-extraction-understanding-merge.test.ts",
  "src/capabilities/conversation/conversation-understanding-regression.test.ts",
  "src/capabilities/conversation/conversation-understanding-product-regression.test.ts",
  "src/capabilities/shared/question-phrasing-acknowledgement.test.ts",
  "src/capabilities/conversation/goal-directed-orchestration-regression.test.ts",
  "src/capabilities/conversation/live-vs-test-divergence-regression.test.ts",
  "src/capabilities/print-validation/print-validation-capability.test.ts",
  "src/capabilities/print-validation/assemble-input.test.ts",
  "src/capabilities/generation-worker/generation-worker-print-validation.test.ts",
  "src/capabilities/final-artwork/final-artwork-capability.test.ts",
  "src/lib/services/final-artwork-service.test.ts",
  "src/app/api/projects/[projectId]/finalize/route.test.ts",
  "src/lib/db/supabase-store.final-artwork.test.ts",
  "src/components/chat/PrepareForPrintAction.test.tsx",
  "src/components/chat/FinalArtworkDeliveryCard.test.tsx",
  "src/lib/services/print-ready-filename.test.ts",
  "src/capabilities/final-artwork/raster-transform.test.ts",
  "src/capabilities/final-artwork/alpha-trim.test.ts",
  "src/capabilities/final-artwork/production-png.test.ts",
  "src/capabilities/final-artwork/production-normalization.test.ts",
  "src/capabilities/final-artwork/local-raster-provider.test.ts",
  "src/capabilities/final-artwork-worker/final-artwork-worker-capability.test.ts",
  "src/lib/config/final-artwork-provider-config.test.ts",
  "src/capabilities/final-artwork/resolve-final-artwork-provider.test.ts",
  "src/capabilities/final-artwork/topaz-transparency-upscale-provider.test.ts",
  "src/capabilities/final-artwork-worker/source-eligibility.test.ts",
  "src/capabilities/final-artwork-worker/production-verification.test.ts",
  "src/lib/config/automated-test-safety.test.ts",
  "src/lib/config/worker-http-batch-policy.test.ts",
  "src/lib/config/local-generation-trigger-policy.test.ts",
  "src/lib/services/local-generation-trigger.test.ts",
  "src/lib/services/local-final-artwork-trigger.test.ts",
  "src/app/api/dev/local-generation-trigger/route.test.ts",
  "src/capabilities/composition-test-safety.test.ts",
  "src/capabilities/generation-worker/generation-worker-claim-init.test.ts",
  "src/app/api/projects/[projectId]/production-artwork/image/route.test.ts",
  "src/app/api/projects/[projectId]/production-artwork/download/route.test.ts",
  "src/capabilities/shared/revision-intent.test.ts",
  "src/capabilities/conversation/rinker-boat-revision-regression.test.ts",
  "src/capabilities/conversation/live-acceptance-corrective-pass-regression.test.ts",
  "src/capabilities/conversation/approval-enqueue-recovery.test.ts",
  "src/capabilities/conversation/revision-enqueue-recovery.test.ts",
  "src/capabilities/shared/revision-delta.test.ts",
  "src/capabilities/providers/openai-concept-provider-edit.test.ts",
  "src/capabilities/prompt-translation/targeted-revision-delta.test.ts",
  "src/capabilities/generation-worker/targeted-revision-source-image.test.ts",
  "src/capabilities/conversation/revision-acknowledgement-delta.test.ts",
  "src/capabilities/conversation/post-revision-chat-state.test.ts",
  "src/capabilities/shared/brief-diff.test.ts",
  "src/capabilities/shared/waiting-copy.test.ts",
  "src/capabilities/shared/production-print-size.test.ts",
  "src/capabilities/conversation/concept-selection-lifecycle.test.ts",
  "src/capabilities/conversation/production-size-lifecycle.test.ts",
  "src/components/chat/PrintReadySizeCard.test.tsx",
  // Existing Artwork → Print Ready Phase 1.
  "src/capabilities/artwork-preparation/upload-security.test.ts",
  "src/capabilities/artwork-preparation/image-analysis.test.ts",
  "src/capabilities/artwork-preparation/background-isolation.test.ts",
  "src/capabilities/artwork-preparation/artwork-preparation-capability.test.ts",
  "src/capabilities/artwork-preparation/bowling-upload-regression.test.ts",
  "src/capabilities/artwork-preparation/no-paid-provider.test.ts",
  // Phase 1 follow-up: enclosed background cavities (letter counters, ring
  // interiors) removed, intentional black artwork preserved.
  "src/capabilities/artwork-preparation/background-cavities.test.ts",
  "src/capabilities/artwork-preparation/bowling-cavity-acceptance.test.ts",
  // Phase 1.2: the three stages that answer the real-file audit — a measured
  // hairline-counter allowance, isolated speckle residue, and user-guided
  // removal of the regions no threshold can safely classify. Deliberately
  // three separate suites, because they are three separate mechanisms.
  "src/capabilities/artwork-preparation/background-speckle.test.ts",
  "src/capabilities/artwork-preparation/guided-removal.test.ts",
  "src/capabilities/artwork-preparation/guided-cleanup-capability.test.ts",
  "src/components/chat/artwork-click-mapping.test.ts",
  "src/components/chat/uploaded-artwork-flow.test.ts",
  "src/components/chat/UploadedArtworkPanel.test.tsx",
  "src/app/api/projects/[projectId]/artwork-upload/route.test.ts",
  // Existing Artwork → Print Ready Phase 2: enhancement decision, production
  // finalization, the uploaded-preserve validation profile, and the synthetic
  // bowling end-to-end acceptance regression.
  "src/capabilities/final-artwork/enhancement-decision.test.ts",
  "src/capabilities/print-validation/uploaded-preserve-profile.test.ts",
  "src/capabilities/final-artwork-worker/prepared-upload-finalization.test.ts",
  "src/capabilities/artwork-preparation/bowling-print-ready-regression.test.ts",
];
